version: '3'
services:
  nginx:
    build: ./nginx
    image: nginx_proxy
    depends_on:
      - node-app
  node-app:
    build: .
    image: emmachid/node-app
    environment:
      - PORT=3000
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_TRACE=true 
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_POLL_INTERVAL=50
volumes:
  mongo-db:
 