version: "3"
services: 
  nodeapp:
    build: .
    ports: 
      - "3000:3000"
      - "4000:8080"
    volumes: 
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
    # env_files:
    #  - ./.env
    
