version: '3'
services:
  nginx:
    build: ./nginx
  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=emmachid
      - MONGO_INITDB_ROOT_PASSWORD=emmy
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
volumes:
  mongo-db:
 